version: '3'
services:
  api:
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - postgres:postgres
    env_file: .env
    command: /usr/local/bin/gunicorn core.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - api:api

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  web-static:
  pgdata:
