# Generated by Django 3.0.8 on 2020-07-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonModel",
            fields=[
                ("person_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("email", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ShareModel",
            fields=[
                ("share_id", models.AutoField(primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=50)),
                ("shares", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("sell", "sell"), ("buy", "buy")],
                        default="buy",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.FloatField()),
                ("amount", models.FloatField()),
                ("currency", models.CharField(max_length=10)),
                ("note", models.CharField(max_length=1000, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person",
                        to="inistock.PersonModel",
                    ),
                ),
            ],
        ),
    ]
