"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from configurations import Configuration
from configurations.values import SecretValue, BooleanValue

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class Production(Configuration):
    SECRET_KEY = SecretValue(
        environ_name="SECRET_KEY", environ_prefix=None, environ_required=True
    )

    DEBUG = BooleanValue(environ_name="DEBUG", environ_prefix=None, default=False)

    ALLOWED_HOSTS = []

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "rest_framework",
        "inistock",
        "corsheaders"
    ]

    MIDDLEWARE = [
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.security.SecurityMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

    ROOT_URLCONF = "core.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "core.wsgi.application"

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": SecretValue(
                environ_name="POSTGRES_DB_NAME",
                environ_prefix=None,
                environ_required=True,
            ),
            "USER": SecretValue(
                environ_name="POSTGRES_DB_USERNAME",
                environ_prefix=None,
                environ_required=True,
            ),
            "PASSWORD": SecretValue(
                environ_name="POSTGRES_DB_PASSWORD",
                environ_prefix=None,
                environ_required=True,
            ),
            "HOST": SecretValue(
                environ_name="POSTGRES_HOST", environ_prefix=None, environ_required=True
            ),
            "PORT": SecretValue(
                environ_name="POSTGRES_PORT", environ_prefix=None, environ_required=True
            ),
        }
    }

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
        {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
        {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
    ]

    REST_FRAMEWORK = {
        "EXCEPTION_HANDLER": "inistock.exceptions.exception_handler.custom_exception_handler"
    }

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    STATIC_URL = "/static/"

    CORS_ORIGIN_ALLOW_ALL = True
    CORS_ALLOW_CREDENTIALS = True

    CORS_ALLOW_HEADERS = [
        'accept',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        "person-id"
    ]
